import numpy as np
nr=int(input("enter the number of rows"))
nc=int(input("enter the number of coloums"))
print('enter the entries in a single line seperated by spaces:')
entries=list(map(int,input().split()))
A=np.array(entries).reshape(nr,nc)
print("matrix x is a follows;",'\n',A)
A_inverse=np.linalg.inv(A)
transpose_of_A_inverse=np.transpose(A_inverse)
determinant_of_A=np.linalg.det(A)
cofactor_of_A=np.dot(transpose_of_A_inverse,determinant_of_A)
print("the cofactor of a matrix is:",'\n',cofactor_of_A)
print("the determinant of a matrix is:",'\n',determinant_of_A)
Adjoint_of_A=np.transpose(cofactor_of_A)
print("the Adjoint of a matrix is:",'\n',Adjoint_of_A)
